name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.build_type }}

    strategy:
      matrix:
        os: [ ubuntu-24.04, ubuntu-24.04-arm, macos-15]
        build_type: [Debug, ASAN, MSAN, UBSAN, Release]
        exclude:
          - os: macos-15
            build_type: MSAN # MSAN is not supported on aarch64 mac

    runs-on: ${{ matrix.os }}

    steps:
      - name: Determine target architecture
        id: arch
        run: |
          case "${{ matrix.os }}" in
          ubuntu-24.04-arm)
           echo "ARCH=aarch64-linux-gnu" >> $GITHUB_ENV
           ;;
          ubuntu-24.04)
           echo "ARCH=x86_64-linux-gnu" >> $GITHUB_ENV
           ;;
          macos-15)
           echo "ARCH=aarch64-darwin" >> $GITHUB_ENV
           ;;
          *)
           echo "ARCH=unknown" >> $GITHUB_ENV
           ;;
          esac

      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Extract version from tag
        uses: damienaicheh/extract-version-from-tag-action@v1.3.0

      - name: Configure CMake
        run: |
          echo "PATCH=$(( ${PATCH:-0} + 1 ))" >> $GITHUB_ENV
          cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DYASER_BUILD_TESTS=ON \
          -DYASER_CERTIFICATE=ON

      - name: Build
        run: |
          ninja -C build
          mv build/src/yaser build/src/yaser-${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}-${{ env.ARCH }}

      - name: Run tests
        if: ${{!(matrix.os == 'ubuntu-24.04-arm' && matrix.build_type == 'ASAN')}} # Causes timeout
        run: |
          cd build
          if [[ "${{ matrix.build_type }}" == "Debug" ]]; then
            ctest --output-on-failure -j 4 -E "UniformRandom3Sat100Vars|Pigeonhole/8|Pigeonhole/9|Pigeonhole/10|Pigeonhole/11"
          else
            ctest --output-on-failure -j 4
          fi

      - name: Verify certificates
        if: ${{!(matrix.os == 'ubuntu-24.04-arm' && matrix.build_type == 'ASAN') && matrix.build_type != 'Debug'}}
        run: |
          curl -L https://www.cs.utexas.edu/\~marijn/drat-trim/drat-trim.c -o drat-trim.c
          gcc -O3 -o drat-trim drat-trim.c

          set -e

          run_one() {
            i="$1"
            path="$2"
            file_name="$3"
            ./drat-trim \
            "./satlib/${path}/${file_name}${i}.cnf" \
            "./build/test/certificates/${file_name}${i}.crt" \
            $4
          }

          export -f run_one

          seq 1 1000 | xargs -n1 -P 4 -I{} bash -c 'run_one "$@" "uniform-random-3-sat/satisfiable" "uf20-0" "-S"' _ {}
          seq 1 1000 | xargs -n1 -P 4 -I{} bash -c 'run_one "$@" "uniform-random-3-sat/satisfiable" "uf50-0" "-S"' _ {}
          seq 1 1000 | xargs -n1 -P 4 -I{} bash -c 'run_one "$@" "uniform-random-3-sat/satisfiable" "uf100-0" "-S"' _ {}
          seq 1 1000 | xargs -n1 -P 4 -I{} bash -c 'run_one "$@" "uniform-random-3-sat/unsatisfiable" "uuf50-0" "-f"' _ {}
          seq 1 1000 | xargs -n1 -P 4 -I{} bash -c 'run_one "$@" "uniform-random-3-sat/unsatisfiable" "uuf100-0" "-f"' _ {}
          seq 1 7 | xargs -n1 -P 4 -I{} bash -c 'run_one "$@" "pigeonhole" "pigeon-" "-f"' _ {}

      - uses: actions/upload-artifact@v4
        if: ${{matrix.build_type == 'Release'}}
        with:
          name: yaser-${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}-${{ env.ARCH }}
          path: build/src/yaser-${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}-${{ env.ARCH }}
