name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.build_type }}

    strategy:
      matrix:
        os: [ ubuntu-24.04, ubuntu-24.04-arm, macos-15]
        build_type: [Debug, Debug_ASAN, Debug_MSAN, Debug_UBSAN, Release]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Determine target architecture
        id: arch
        run: |
          case "${{ matrix.os }}" in
          ubuntu-24.04-arm)
           echo "ARCH=aarch64-linux-gnu" >> $GITHUB_ENV
           ;;
          ubuntu-24.04)
           echo "ARCH=x86_64-linux-gnu" >> $GITHUB_ENV
           ;;
          macos-15)
           echo "ARCH=aarch64-darwin" >> $GITHUB_ENV
           ;;
          *)
           echo "ARCH=unknown" >> $GITHUB_ENV
           ;;
          esac

      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Extract version from tag
        uses: damienaicheh/extract-version-from-tag-action@v1.3.0

      - name: Configure CMake
        run: |
          echo "PATCH=$(( ${PATCH:-0} + 1 ))" >> $GITHUB_ENV
          cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DYASER_BUILD_TESTS=ON

      - name: Build
        run: |
          ninja -C build
          mv build/src/yaser build/src/yaser-${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}-${{ env.ARCH }}

      - name: Run tests
        run: |
          cd build
#          ctest --output-on-failure

      - uses: actions/upload-artifact@v4
        if: ${{matrix.build_type == 'Release'}}
        with:
          name: yaser-${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}-${{ env.ARCH }}
          path: build/src/yaser-${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}-${{ env.ARCH }}
