name: Release

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'mainline' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Extract version from tag
        uses: damienaicheh/extract-version-from-tag-action@v1.3.0

      - name: Set next version
        id: version
        run: |
          NEXT_VERSION="${MAJOR}.${MINOR}.$((PATCH + 1))"
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV

      - name: Generate release notes
        run: |
          git log $MAJOR.$MINOR.$PATCH..HEAD --pretty=format:"- %s ([\`%h\`](https://github.com/${GITHUB_REPOSITORY}/commit/%H))" > release_notes.md
          cat release_notes.md

      - uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NEXT_VERSION }}
          name: Release ${{ env.NEXT_VERSION }}
          body_path: release_notes.md
          draft: false
          prerelease: false
          files: |
            yaser-${{ env.NEXT_VERSION }}-aarch64-darwin/yaser-${{ env.NEXT_VERSION }}-aarch64-darwin
            yaser-${{ env.NEXT_VERSION }}-aarch64-linux-gnu/yaser-${{ env.NEXT_VERSION }}-aarch64-linux-gnu
            yaser-${{ env.NEXT_VERSION }}-x86_64-linux-gnu/yaser-${{ env.NEXT_VERSION }}-x86_64-linux-gnu
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
